### ISSUE TITLE
[bug] cannot instrument openai in colab unless colab session is restarted after pip install

### ISSUE THREAD

**Issue by RogerHYang** [Arize-ai/openinference#100]
openai instrumentation fails in a fresh session of colab.

It only works after the session is restarted after pip install.

## Workaround
Use [`skip_dep_check=True`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/42faa1a34a711c35576833e56d0e28ea0cae4993/opentelemetry-instrumentation/src/opentelemetry/instrumentation/instrumentor.py#L104)
```python
OpenAIInstrumentor().instrument(skip_dep_check=True)
```

## Screenshot
<img width="1597" alt="Screenshot 2024-01-11 at 12 27 41 PM" src="https://github.com/Arize-ai/openinference/assets/80478925/c83763d8-f1c9-47ed-b599-79192d5eed97">

## Code
```python
%pip install -qqq openinference-instrumentation-openai opentelemetry-instrumentation-httpx opentelemetry-sdk opentelemetry-exporter-otlp arize-phoenix openai
```

```python
from openinference.instrumentation.openai import OpenAIInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import SimpleSpanProcessor

resource = Resource(attributes={})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_exporter = OTLPSpanExporter(endpoint="http://127.0.0.1:6006/v1/traces")
span_processor = SimpleSpanProcessor(span_exporter=span_exporter)
tracer_provider.add_span_processor(span_processor=span_processor)
trace_api.set_tracer_provider(tracer_provider=tracer_provider)

HTTPXClientInstrumentor().instrument()
OpenAIInstrumentor().instrument()
```

**Comment by RogerHYang** [comment]
Note that the default version in Colab for `typing-extensions is 4.5.0`. But openai requires [>=4.7](https://github.com/openai/openai-python/blob/3fb66ddd5e2b6810f9f11619302a8b82d3712f10/pyproject.toml#L13). Since the error message mentions `typing-extensions 4.5.0`. Something was problem broken during the installation process, and was fixed by restarting the session.

**Comment by RogerHYang** [comment]
The alternative is to use [`skip_dep_check=True`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/42faa1a34a711c35576833e56d0e28ea0cae4993/opentelemetry-instrumentation/src/opentelemetry/instrumentation/instrumentor.py#L104)
```python
OpenAIInstrumentor().instrument(skip_dep_check=True)
```

**Comment by RogerHYang** [comment]
Similar problem with other instrumentors (i.e. session needs restart after pip install)

<img width="1219" alt="Screenshot 2024-01-24 at 9 55 59 AM" src="https://github.com/Arize-ai/openinference/assets/80478925/3be317df-1d2c-45fb-8718-053d3543afbc">

**Comment by axiomofjoy** [comment]
I wonder if something like this is an alternative. https://ipython.org/ipython-doc/3/config/extensions/autoreload.html

**Comment by mikeldking** [comment]
skip deps check is built into phoenix wrappers
