### ISSUE TITLE
Lib is resetting ROOT Logger to level INFO

### ISSUE THREAD

**Issue by armoucar-neon** [Arize-ai/openinference#1000]
https://github.com/Arize-ai/openinference/blame/c2b94cd6676131807d294045372b500293b47917/python/openinference-instrumentation/src/openinference/instrumentation/logging.py#L11-L12

Hi guys, this line is resetting the root logger level. So first thing I do in my app is configuring logs, then I import stuff later and this resets my root logger configuration level.

**Comment by mikeldking** [comment]
thanks for the catch @armoucar-neon !
