### ISSUE TITLE
[bug] OpenAI Node AutoInstrumentation not Exporting Spans

### ISSUE THREAD

**Issue by Jeffrey-Peng** [Arize-ai/openinference#1030]
**Describe the bug**
the openai node autoinstrumentor is not creating or exporting spans - this doesn't seem to be an issue with ingestion as the spans are also not showing up in the console

**Expected behavior**
open ai autoinstrumentor should create spans that can then be exported

**Desktop (please complete the following information):**
 - this is happening in a lambda

**Additional context**
reach out to @Parker-Stafford  for more information

**Comment by Parker-Stafford** [comment]
this is not a bug within the instrumentor but due to some dependency issue with using the grpc exporter in an aws lambda, closing
