### ISSUE TITLE
[feature request] add support for Mistral agents.complete

### ISSUE THREAD

**Issue by Jgilhuly** [Arize-ai/openinference#1033]
**Is your feature request related to a problem? Please describe.**
Our current Mistral instrumentation traces calls to `Mistral.chat.` methods complete, complete_async, stream, and stream_async. Mistral uses separate `Mistral.agent.` methods for any calls to agents defined with Mistral ([ref](https://github.com/mistralai/client-python/blob/main/src/mistralai/agents.py)). This means that our instrumentor is not collecting traces from any Mistral agent applications.

**Describe the solution you'd like**
Can we add tracing support for mistral's agent calls to our instrumentor?

Example notebook trying to trace a mistral agent: https://colab.research.google.com/drive/1GrN05FFBmcAmbu50h6UnVnOblj9QlMgE?usp=sharing

**Comment by harrisonchu** [comment]
https://github.com/Arize-ai/openinference/pull/1043

**Comment by mikeldking** [comment]
Closing as done. Will publish
