### ISSUE TITLE
DSPy version 2.5 onward logging not compatible with Phoenix

### ISSUE THREAD

**Issue by arthurgreef** [Arize-ai/openinference#1050]
**Is your feature request related to a problem? Please describe.**
Version 2.5 of the DSPy library is not supported by the `openinference-instrumentation-dspy` library.

**Describe the solution you'd like**
Add support for DSPy 2.5 to the `openinference-instrumentation-dspy` library..

**Describe alternatives you've considered**
None.

**Additional context**
DSPy is now using LightLLM for clients and this broke backward compatibly with tracing libraries.

**Comment by okhat** [comment]
We're happy to support this! Users love the Phoenix <> DSPy integration.

**Comment by mikeldking** [comment]
thanks for the issue @okhat @arthurgreef - We will dive in next week and get a fix out. We also have tracing for LiteLLM so this might work out nicely.
