### ISSUE TITLE
[Bug] Groq Client Not Displaying Tool Choices in Tracing Dashboard

### ISSUE THREAD

**Issue by SiyuanQi** [Arize-ai/openinference#1102]
When using the Groq client (AsyncGroq) in conjunction with the tracing dashboard, tool choices and other function-call-specific details are not displayed as expected. This behavior persists even after upgrading `arize-phoenix` to version 5.6.0, which was expected to introduce support for tool role messages and spans.

However, **switching from the Groq client (AsyncGroq) to the OpenAI client (AsyncOpenAI)** seems to resolve the issue, suggesting a possible instrumentation incompatibility.

More context and reproducing details can be seen [here](https://github.com/Arize-ai/phoenix/issues/5260).

Versions:
`openinference-instrumentation-openai`: `0.1.17`
`openinference-instrumentation-groq`: `0.1.4`

**Comment by RogerHYang** [comment]
Thank you for the report. We'll have someone work on this next week.

**Comment by SiyuanQi** [comment]
Thank you for following up on this – I appreciate it!
