### ISSUE TITLE
[feature request]: add get_current_span for LlamaIndexInstrumentor

### ISSUE THREAD

**Issue by Mosquid** [Arize-ai/openinference#1104]
**Is your feature request related to a problem? Please describe.**
I'm trying to build an endpoint that will allow me to capture user feedback. For that, I need to know the current span ID.

**Describe the solution you'd like**
Adding a method to `LlamaIndexInstrumentor` to get the current span would help.

**Comment by axiomofjoy** [comment]
hi @Mosquid, can you try the following?

```
from opentelemetry import trace

# Get the current span
current_span = trace.get_current_span()

if current_span:
    # Retrieve the span ID
    span_id = current_span.get_span_context().span_id
    print(f"Current Span ID: {span_id}")
```

**Comment by Mosquid** [comment]
Hi @axiomofjoy,

Thanks for your reply. Yes, I tried to get the current span that way. However, here's what I get:

```
NonRecordingSpan(SpanContext(trace_id=0x00000000000000000000000000000000, span_id=0x0000000000000000, trace_flags=0x00, trace_state=[], is_remote=False))
```

I found a workaround, sort of:
```
with tracer.start_as_current_span("question-answering", ) as span...
```

But then I can't set the span kind to `CHAIN`

**Comment by Mosquid** [comment]
UPD: 

I was able to solve it using `span.set_attribute(OPENINFERENCE_SPAN_KIND, SpanKind.CHAIN.value)` 
But I think it would be nice to try to make `trace.get_current_span` to work with the llama-index instrumentor
