### ISSUE TITLE
[feature request] add dify intergration support

### ISSUE THREAD

**Issue by wy96f** [Arize-ai/openinference#1107]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Do you have plans to support dify(https://github.com/langgenius/dify)? It is also a popular open-source project that many people are using.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by RogerHYang** [comment]
Thank you for filing the issue. We'll track this via https://github.com/Arize-ai/phoenix/issues/5299 going forward.
