### ISSUE TITLE
[feature request] Support Hiding Invocation Parameters in Spans

### ISSUE THREAD

**Issue by rajaswa** [Arize-ai/openinference#1170]
**Is your feature request related to a problem? Please describe.**
Currently there is no support to hide invocation parameters in Spans - which might contain sensitive information like api_keys.

**Describe the solution you'd like**
The `TraceConfig` class can start supporting a `hide_invocation_params` property, which will REDACT invocation parameters.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by axiomofjoy** [comment]
@rajaswa Are you seeing anywhere that we store API keys in spans? This is a mistake if so.

**Comment by rajaswa** [comment]
> @rajaswa Are you seeing anywhere that we store API keys in spans? This is a mistake if so.

@axiomofjoy Yes, I am seeing `api_key` being logged in the Spans UI under `Invocation Params` tab with the below schema (this is for DSPy with LiteLLM-based Azure OpenAI LLM Call)

```json
{
  "num_retries": 3,
  "cache": {
    "no-cache": true,
    "no-store": true
  },
  "temperature": 0.3,
  "max_tokens": 4096,
  "api_base": "<my-azure-openai-url",
  "api_version": "2024-06-01",
  "api_key": "my-azure-openai-key"
}
```

**Comment by rajaswa** [comment]
Thanks @RogerHYang! I have updated the Phoenix docs with the same, hope it helps! - https://github.com/Arize-ai/phoenix/pull/5739
