### ISSUE TITLE
[bug] output from llama_index tracing doesn't propagate up to the agent

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#154]
See screenshot. I think for streaming specifically
<img width="1899" alt="Screenshot 2024-01-26 at 12 44 08 PM" src="https://github.com/Arize-ai/openinference/assets/5640648/149f68b9-eae1-46f8-b949-cf7542dd04de">

steps to reproduce:
- run the llama_index example app.

**Comment by RogerHYang** [comment]
This is because the agent has a separate code path for the streaming response that is not detected by our methods, and is  very difficult to monkey patch.

**Comment by edhenry** [comment]
Would this also be the root cause of the issue I'm seeing here:

![image](https://github.com/Arize-ai/openinference/assets/5572998/f36c0e50-ea36-4728-bbaf-1c215ac90574)


Where I can trace the entire set of calls, end-to-end, but when using them as part of an `ChatEngine` subclassed from `BaseChatEngine` I am getting split traces between the embedding/retrieval calls, and the LLM call.

**Comment by mikeldking** [comment]
> Would this also be the root cause of the issue I see here?:
> 
> ![image](https://private-user-images.githubusercontent.com/5572998/302792106-f36c0e50-ea36-4728-bbaf-1c215ac90574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjMwOTYsIm5iZiI6MTcwNzI2Mjc5NiwicGF0aCI6Ii81NTcyOTk4LzMwMjc5MjEwNi1mMzZjMGU1MC1lYTM2LTQ3MjgtYmJhZi0xYzIxNWFjOTA1NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMjMzOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjUyZDlhOGNmZTA1OWM3YjE5NDcyZjI4Njg3NTNhZTgyOTE2YThiNDBkZDE1NzE2NDE5NDc0ODc2NDY5ZWI1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mZ5zeQKiHTTRwpTBeU3fjUuj9WFWyv687gYYEupDEmw)
> 
> Where I can trace the entire set of calls end-to-end, but when using them as part of a `ChatEngine` subclassed from `BaseChatEngine`, I am getting split traces between the embedding/retrieval calls and the LLM call.

@edhenry I've never seen the tool you're using in the screenshot! Are you using OpenInference with jaeger?

I'd be surprised if these issues are related as this ticket is mainly around not being able to propagate the output of a streaming llm response to a root span that is an `agent`. However you never know! Could you share a bit of the code for your `ChatEngine`?

**Comment by RogerHYang** [comment]
> I am getting split traces

Split traces is usually a symptom of an issue of callback manager in Llama-Index. We would love it if you could open a issue with further details on that. Thanks.

**Comment by edhenry** [comment]
I can confirm it was related to how I was structuring some of my objects. Apologies for jumping in on this issue as it isn't related!

**Comment by mikeldking** [comment]
Punting as callbacks are being deprecated
