### ISSUE TITLE
[bug] Ensure that both langchain and llamaIndex dump prompt template variables as kv pairs

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#191]
In order to re-play a prompt and apply variables consistently, we must dump the variables in a consistent format so that it can be applied to the template:

E.x.

prompt_template: `tell me a {type} joke`
variables: { type: "funny" }

**Comment by RogerHYang** [comment]
for langchain, we have to put these two pieces together manually

<img width="660" alt="Screenshot 2024-02-08 at 10 19 04 AM" src="https://github.com/Arize-ai/openinference/assets/80478925/c8776a43-6873-4209-9c59-fd75d353784d">
