### ISSUE TITLE
[bug] LangChain tracer is serializing the MIME type as the enum string, not a real MIME type

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#225]
<img width="1066" alt="Screenshot 2024-02-15 at 4 52 51 PM" src="https://github.com/Arize-ai/openinference/assets/5640648/cd190d60-c077-45b1-8d63-91e730a7868f">

Should be a real mime type: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

**Comment by RogerHYang** [comment]
this is our [internal](https://github.com/Arize-ai/phoenix/blob/fce2d63983aa31b115080d94bb3f5c7a899ecaf5/src/phoenix/trace/otel.py#L73) enum after ingestion

**Comment by RogerHYang** [comment]
see console logger

<img width="387" alt="Screenshot 2024-02-15 at 3 58 32 PM" src="https://github.com/Arize-ai/openinference/assets/80478925/5628b6e7-e5c4-4b18-87ec-bb0a0bcbb199">

**Comment by RogerHYang** [comment]
this is for backward compatibility. not a bug

**Comment by mikeldking** [comment]
> see console logger
> 
> 
> 
> <img width="387" alt="Screenshot 2024-02-15 at 3 58 32 PM" src="https://github.com/Arize-ai/openinference/assets/80478925/5628b6e7-e5c4-4b18-87ec-bb0a0bcbb199">
> 
> 

Oh interesting, got it. Maybe we can make them align better. Will close
