### ISSUE TITLE
[bug] [langchain] trace for ConversationalRetrievalWithScoreChain is missing retriever spans

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#239]
**Describe the bug**

**To Reproduce**
Invoke a chain such as ConversationalRetrievalWithScoreChain

```python
chain = create_conversational_retrieval_with_score_chain(
11m=self. llm, chain_type=self.chain_type
)
```

**Expected behavior**
The trace should contain retrievers

**Screenshots**
https://arize-ai.slack.com/files/U06KLPWF5FY/F06LJDWDV6V/image.png?origin_team=T0175GWSS8N&origin_channel=C04QMRADE1L

**Additional context**
possible chain: https://js.langchain.com/docs/modules/chains/popular/chat_vector_db

**Comment by RogerHYang** [comment]
customer resolved the issue after adding the callback manager back to the subclass method in a way similar to that shown [here](https://github.com/langchain-ai/langchain/blob/e237dcec9190cbd8dc075274784e30252f26730e/libs/core/langchain_core/retrievers.py#L220-L233)
