### ISSUE TITLE
🗺️ LlamaIndex instrumentation based tracing

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#288]
Scope out a strategy where we can have both callbacks and instrumentation simultaneously and we can switch to instrumentation incrementally.

**Comment by RogerHYang** [comment]
blocked by the lack of the payload object in `span_enter`

**Comment by mikeldking** [comment]
Should be un-blocked next week.

**Comment by mikeldking** [comment]
Events are now typed: https://github.com/run-llama/llama_index/pull/13302

Example instrumentation notebook: https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/instrumentation/instrumentation_observability_rundown.ipynb
