### ISSUE TITLE
[js][langchain] instrumentation

### ISSUE THREAD

**Issue by gkgourav45** [Arize-ai/openinference#316]
**Is your feature request related to a problem? Please describe.**
Unable to log traces/span for llm application build in nextjs that is using langchain, azure openai

**Describe the solution you'd like**
js langchain instrumention similar to python

**Describe alternatives you've considered**
"@traceloop/instrumentation-langchain"
**Additional context**
need just langchain related traces and spans with all fields(name, kind, input, output, latency, total_tokens) populated in phoenix similar to python langchaininstrumentor described in https://docs.arize.com/phoenix/tracing/how-to-tracing/instrumentation/langchain

**Comment by mikeldking** [comment]
Hey @gkgourav45 we just launched langchainJS! Check it out and let us know how it goes!
https://www.npmjs.com/package/@arizeai/openinference-instrumentation-langchain
https://github.com/Arize-ai/openinference/tree/main/js/examples/langchain-express
