### ISSUE TITLE
[bug] trace tree broken for llama-index example

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/openinference#368]
**Describe the bug**
Trace tree is broken on example in `python/examples/llama-index`:
- llm spans are orphaned
- no top-level agent span is appearing, we just have a retriever span at the top level

<img width="1592" alt="Screenshot 2024-04-11 at 10 19 48 AM" src="https://github.com/Arize-ai/openinference/assets/15664869/151e30ba-190e-47df-ac02-03194a4c110a">

**To Reproduce**
Run `docker compose up --build` in `python/examples/llama-index`.

**Expected behavior**
Trace tree should be intact.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version:

**Comment by mikeldking** [comment]
I can confirm that even on the latest llama-index create llama example things are not great.

I added the debug handler and this is what it should look like

llama-index-backend-1   | Trace: chat
llama-index-backend-1   |     |_CBEventType.TEMPLATING ->  0.000455 seconds
llama-index-backend-1   |     |_CBEventType.LLM ->  1.820308 seconds
llama-index-backend-1   |     |_CBEventType.RETRIEVE ->  0.209598 seconds
llama-index-backend-1   |       |_CBEventType.EMBEDDING ->  0.191755 seconds
llama-index-backend-1   |     |_CBEventType.LLM ->  0.0 seconds
llama-index-backend-1   | **********
