### ISSUE TITLE
[bug] python/openinference-instrumentation/src/openinference/instrumentation/__init__.py does not conform to namespace packaging

### ISSUE THREAD

**Issue by ewianda** [Arize-ai/openinference#398]
**Describe the bug**
Based on 

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages
```
It is extremely important that every distribution that uses the namespace package omits the __init__.py 
or uses a pkgutil-style __init__.py. If any distribution does not, it will cause
 the namespace logic to fail and the other sub-packages
 will not be importable.
```
OR

[native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages). 

Without this we get 

```
    from openinference.instrumentation.llama_index import LlamaIndexInstrumentor                                                                                                                            
ModuleNotFoundError: No module named 'openinference.instrumentation.llama_index' 
```

when  openinference-instrumentation  and openinference.instrumentation-llama_index are used together

**Additional context**
Similar issue https://github.com/aws/jsii/issues/3881

**Comment by RogerHYang** [comment]
Hi @ewianda I am not able to reproduce this issue. As shown in the screenshot below, it has no issue on colab.

Do you ave more context on where the failure occured? (Are you using editable install?)

<img width="806" alt="Screenshot 2024-04-23 at 1 54 47 PM" src="https://github.com/Arize-ai/openinference/assets/80478925/83e23f8f-78cd-46d1-8311-4e71546f912c">

**Comment by ewianda** [comment]
Sorry for the late response. This issue will not be observed when running a pip install or any other package manager. This is primarily a problem with bazel build tool that attempts to reconstruct the python path with the assumption that all namespace packages conform to the standard packaging

**Comment by axiomofjoy** [comment]
@ewianda Thanks for the reply. Can you give us more detailed information on when exactly you hit this issue? E.g., are you using Bazel to build an OCI image with both `openinference-instrumentation` and `openinference-instrumentation-llama-index` at the same time?

**Comment by ewianda** [comment]
No, it is just a regular py_binary. I can create a GitHub repo to quickly demonstrate the issue if that helps

**Comment by ewianda** [comment]
we are using the this patch to get around the issue

```diff
--- a/openinference/instrumentation/__init__.py
+++ b/openinference/instrumentation/__init__.py
@@ -1,3 +1,4 @@
+__path__ = __import__('pkgutil').extend_path(__path__, __name__)
 import contextlib
 from typing import Iterator

**Comment by RogerHYang** [comment]
Based on this [reading](https://github.com/aws/jsii/pull/4437/files#diff-f7a931af3b21698bee9fa2730cdaa8d440e4c596348770339f0187ff7ae34752R1704), it is an problem specific to Bazel and is otherwise working as intended for Python. So I am not sure how we should be supporting this going forward.

**Comment by ewianda** [comment]
Wil not be possible to apply the above patch as a solution ?

**Comment by axiomofjoy** [comment]
@ewianda I'm not a Bazel expert, but curious if you've given [this](https://github.com/bazelbuild/rules_python/issues/93#issuecomment-710085646) a shot as an approach for handling namespaced packages?

**Comment by ewianda** [comment]
yeah the solution in the post is already implemented in bazel, the relevant logic is 

https://github.com/bazelbuild/rules_python/blob/397c1b17d04af195eb62bf8645b4d820eb4b21e7/python/pip_install/tools/wheel_installer/namespace_pkgs.py#L74-L99

```python
def add_pkgutil_style_namespace_pkg_init(dir_path: Path) -> None:
    """Adds 'pkgutil-style namespace packages' init file to the given directory


    See: https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages


    Args:
        dir_path: The directory to create an __init__.py for.


    Raises:
        ValueError: If the directory already contains an __init__.py file
    """
    ns_pkg_init_filepath = os.path.join(dir_path, "__init__.py")


    if os.path.isfile(ns_pkg_init_filepath):
        raise ValueError("%s already contains an __init__.py file." % dir_path)


    with open(ns_pkg_init_filepath, "w") as ns_pkg_init_f:
        # See https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages
        ns_pkg_init_f.write(
            textwrap.dedent(
                """\
                # __path__ manipulation added by bazelbuild/rules_python to support namespace pkgs.
                __path__ = __import__('pkgutil').extend_path(__path__, __name__)
                """
            )
        )
        
        As you can see the logic expects that namespace packages should have no `__init__.py` file which is the case for all the packages here
        
        https://github.com/Arize-ai/openinference/tree/main/python/instrumentation
        
        That is the reason why the above patch is the solution to the problem from bazel

**Comment by RogerHYang** [comment]
> That is the reason why the above patch is the solution to the problem from bazel

Our packages sharing the same namespace does not automatically make them "namespace packages". They're intended to be installed and used as "regular packages", and are configured as such (see [PEP 420](https://peps.python.org/pep-0420/#:~:text=Regular%20packages%20are%20self%2Dcontained%3A%20all%20parts%20live%20in%20the%20same%20directory%20hierarchy.) shown below). They only become "namespace packages" as a result of Bazel's operating requirements, which was not factored into our original design. This is _not_ to say that we wouldn't consider modifications in light of this new limitation, but I think we'll need some time to think this one through.

<img width="822" alt="Screenshot 2024-04-26 at 9 33 10 PM" src="https://github.com/Arize-ai/openinference/assets/80478925/4c2e36b2-a6eb-4636-8927-2ee596b2b8c8">
