### ISSUE TITLE
[bug] DSPy fails with cohere due to serialization issues

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#405]
https://colab.research.google.com/drive/1CqdTV2hscKBRkyTcjPOQw_-uZXeeAHyE?usp=sharing

**Comment by axiomofjoy** [comment]
@mikeldking let me know if you need me to take a look at this one

**Comment by mikeldking** [comment]
> @mikeldking let me know if you need me to take a look at this one

@axiomofjoy that would be amazing. It was reported in the DSPy discord and I can pick it up tonight if you don’t get to it

**Comment by axiomofjoy** [comment]
@mikeldking Pushed a fix

**Comment by mikeldking** [comment]
> @mikeldking Pushed a fix

❤️‍🔥
