### ISSUE TITLE
[feature request] Add support for Bedrock Meta models

### ISSUE THREAD

**Issue by krzysztofspalinski** [Arize-ai/openinference#447]
Current version of `openinference-instrumentation-bedrock` doesn't support intercepting output of Meta models (Llama 2 and 3) running on AWS Bedrock. As we can see [here](https://github.com/Arize-ai/openinference/blob/main/python/instrumentation/openinference-instrumentation-bedrock/src/openinference/instrumentation/bedrock/__init__.py#L144), currently output is only extracted from `ai21`, `anthropic` and `cohere` vendors. 

A desired solution would allow intercepting output from Meta (and potentially other vendors) available through Bedrock.

**Comment by axiomofjoy** [comment]
@krzysztofspalinski Thanks for request, makes sense.
