### ISSUE TITLE
[feature request] Vercel AI SDK Autoinstrumentor

### ISSUE THREAD

**Issue by trevor-laviale-arize** [Arize-ai/openinference#490]
**Is your feature request related to a problem? Please describe.**
For teams using the Vercel AI SDK in their GenAI apps, we need to use the manual instrumentation for tracing.

**Describe the solution you'd like**
It would be nice to have an autoinstrumentor for the [Vercel AI SDK](https://sdk.vercel.ai/docs/ai-sdk-core) rather than needing to manually instrument these use cases.

**Describe alternatives you've considered**
Manual instrumentation

**Comment by mikeldking** [comment]
We are going the route of a span processor for now. closing as duplicate of #785
