### ISSUE TITLE
🗺️ Haystask Instrumentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#524]
Instrumentation for [Haystack](https://haystack.deepset.ai/)

- [x] #826
- [x] #887
- [x] #822
- [ ] #823
- [x] #889
- [x] #882
- [x] #886
- [x] #814
- [x] #815
- [x] #824
- [x] #883
- [x] #825
- [x] #807
- [x] #884
- [x] #888
- [x] #885
- [x] #951
- [x] #957

**Comment by mikeldking** [comment]
Unknown span kinds show up for instrumentation
<img width="2055" alt="Screenshot 2024-08-07 at 1 41 16 PM" src="https://github.com/user-attachments/assets/1bad3611-c040-4038-93af-52295a8d9f81">

**Comment by mikeldking** [comment]
Pipeline missing output
<img width="1685" alt="Screenshot 2024-08-07 at 2 17 02 PM" src="https://github.com/user-attachments/assets/996dde2c-e014-4c59-a268-a13cbb251563">

**Comment by mikeldking** [comment]
LLM call doesn't match OTEL syntax for the name: 
<img width="527" alt="Screenshot 2024-08-07 at 2 17 42 PM" src="https://github.com/user-attachments/assets/079aa278-20b1-4af0-956e-be8e1bd130f3">

**Comment by mikeldking** [comment]
Output messages is a string rather than a list of messages, causing pheonix to crash - this is using the quickstart
<img width="343" alt="Screenshot 2024-08-07 at 2 18 54 PM" src="https://github.com/user-attachments/assets/d9ed4db0-f12c-4cb4-b312-a37a55838bf8">

**Comment by Parker-Stafford** [comment]
input to retriever is embedding - might want to opt for the query string if possible here? not sure what the best thing to do is here

![image](https://github.com/user-attachments/assets/0536d98a-a808-449e-8c4c-118274d15610)

**Comment by Parker-Stafford** [comment]
> Pipeline missing output <img alt="Screenshot 2024-08-07 at 2 17 02 PM" width="1685" src="https://private-user-images.githubusercontent.com/5640648/355975224-996dde2c-e014-4c59-a268-a13cbb251563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjIxNDYsIm5iZiI6MTcyMzA2MTg0NiwicGF0aCI6Ii81NjQwNjQ4LzM1NTk3NTIyNC05OTZkZGUyYy1lMDE0LTRjNTktYTI2OC1hMTNjYmIyNTE1NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMjAxNzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQzM2Q3ZjEwNTg4ZjZhZmRlNGMxNGFlMTYwNmUyYmY1ZTg3MDZiNGYwOGUzZDhhNjNkZjdmYWMxODhlODFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e18llgszvrTQLb2-PXXySv2hq62wGKqO5yme38Kt-eY">

also happening on this tutorial https://haystack.deepset.ai/tutorials/27_first_rag_pipeline

**Comment by Parker-Stafford** [comment]
getting llmAttributes[LLMAttributePostfixes.output_messages]?.map is not a function this means we're expecting a list but getting something else when clicking on the llm span this tutorial: 

https://haystack.deepset.ai/tutorials/27_first_rag_pipeline

![image](https://github.com/user-attachments/assets/83d94ba7-3daa-4bc6-afe6-53d8317895bd)

**Comment by Parker-Stafford** [comment]
this might be correct, not sure how haystack pipelines work but there is no hierarchy in the spans here, typically i feel like there is a little bit of nesting here

![image](https://github.com/user-attachments/assets/7d7db57a-933a-4aa5-ad90-340e24bb7466)

**Comment by Jgilhuly** [comment]
Function / tool calling spans don't appear in Phoenix. Here's the trace for an invocation of the function calling tutorial at https://haystack.deepset.ai/tutorials/40_building_chat_application_with_function_calling

<img width="598" alt="Screenshot 2024-08-07 at 1 38 03 PM" src="https://github.com/user-attachments/assets/08ff5986-ad5c-4f05-a345-4ff8264a4b05">

Need to add support for tool calling

**Comment by Parker-Stafford** [comment]
not sure what the best solution is here but this might need some work, there are no prompt template variables in the prompt_template block of attributes, there are retrieval documents though which do seem to be passed in to the template. 
 I would expect to see {{question}} in the vars at least and maybe the documents

![image](https://github.com/user-attachments/assets/9c967b81-a1a0-4063-9f98-11a30df54063)

**Comment by mikeldking** [comment]
<img width="1924" alt="Screenshot 2024-08-07 at 2 45 06 PM" src="https://github.com/user-attachments/assets/21c21c33-e5a2-46bb-91fd-af03f299fe85">
Haystack component run shows up as leaf nodes (looks like it's OTEL).

**Comment by cjunkin** [comment]
![Screenshot 2024-08-07 at 1 46 22 PM](https://github.com/user-attachments/assets/ef93e2b6-53b1-4983-a07f-51b06fc8658a)
![Screenshot 2024-08-07 at 1 46 31 PM](https://github.com/user-attachments/assets/1546a6bb-2472-4a4c-becd-425f826d61fd)

opening OpenAIGenerator span causes error

**Comment by cjunkin** [comment]
![Screenshot 2024-08-07 at 1 47 54 PM](https://github.com/user-attachments/assets/eec8addf-7e29-4b29-ae18-6f41bc9f98ca)
![Screenshot 2024-08-07 at 1 48 50 PM](https://github.com/user-attachments/assets/8be1dcd2-9303-4bff-82e1-55f2673a93fb)

Not sure if this is the desired formatting

**Comment by axiomofjoy** [comment]
![Screenshot 2024-08-07 at 1 45 56 PM](https://github.com/user-attachments/assets/eb8846f8-fd54-4ac2-b516-c1685c9b7697)

- unknown span kinds
- clicking through on `OpenAIGenerator` results in `C.map is not a function` error
- missing outputs in spans

**Comment by cjunkin** [comment]
![Screenshot 2024-08-07 at 1 56 09 PM](https://github.com/user-attachments/assets/e5572be7-71c6-4371-b346-e7b59c198599)

Empty/null attributes

**Comment by Parker-Stafford** [comment]
Query is lost in final llm call when running this example : https://docs.haystack.deepset.ai/docs/lostinthemiddleranker#in-a-pipeline

![image](https://github.com/user-attachments/assets/967546ab-5e4b-4cab-8163-08bedb8951a6)


Templating is a little off but this is a larger product / design issue see screen shot (no variables / template but variables and template in the Prompt template tab)

![image](https://github.com/user-attachments/assets/9a3e1f7a-a31f-44e8-87d9-8808b884297f)

Small note this reranker doesn't require a query because it assumes the documents are already ordered by relevance and just takes those documents and places the most important (first) ones at the edges of the context - this makes the ui look a little weird with the empty query

![image](https://github.com/user-attachments/assets/87e2b09a-a325-4f98-81db-86c5a7d040d7)

**Comment by mikeldking** [comment]
@axiomofjoy conda forge

**Comment by mikeldking** [comment]
Only thing remaining is opentelemetry.io closing
