### ISSUE TITLE
🗺️ Vercel AI SDK Instrumentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#533]
Is your feature request related to a problem? Please describe.
For teams using the Vercel AI SDK in their GenAI apps, we need to use the manual instrumentation for tracing.

Describe the solution you'd like
It would be nice to have an autoinstrumentor for the [Vercel AI SDK](https://sdk.vercel.ai/docs/ai-sdk-core) rather than needing to manually instrument these use cases.

Describe alternatives you've considered
Manual instrumentation

**Comment by Parker-Stafford** [comment]
closed in https://github.com/Arize-ai/openinference/pull/879
