### ISSUE TITLE
[bug] possible missing langraph tokencounts

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#545]
Report of missing token counts using langraph

GPT and langgraph version==0.0.32.
for referance you can see this collab
https://colab.research.google.com/drive/1xDEPe2i_2rRqs7o6oNTtqA4J7Orsnvx1?usp=sharing

**Comment by RogerHYang** [comment]
I had a direct message conversation with the user. They are actually not using the same code as the one in the colab (the colab works fine and has token counts), but the user is using something that's calling the LLM with the streaming option and streaming doesn't return token counts in general.
