### ISSUE TITLE
[bug] Datasets Page Doesn't Refresh Realtime, I have to manually refresh page

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/openinference#611]
When I upload a dataset I have to refresh the page to see the new dataset, vs it just showing up automatically real time.

<img width="1627" alt="Screenshot 2024-07-20 at 10 28 35 AM" src="https://github.com/user-attachments/assets/7a28771e-ae51-4a79-9dd1-39874a383829">

**Comment by mikeldking** [comment]
Wrong repo
