### ISSUE TITLE
[bug] - Dataset Throws an Error with Prompt Variable column

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/openinference#612]
This works with Phoenix but Arize throws an error. The error is very cryptic as well, we need to also print a better error of what column is causing the issue. In order to track down the column I had to manually remove them to find the error.

Works removing that column, fails with just the variables column. This should work.

https://colab.research.google.com/drive/1zVGOc1zFAuvRWgU5fvwhswMyuu4LIJR9?usp=sharing

<img width="1504" alt="Screenshot 2024-07-20 at 11 02 45 AM" src="https://github.com/user-attachments/assets/c4bda556-27db-4faf-acb2-a355005323ca">
<img width="1732" alt="Screenshot 2024-07-20 at 11 02 39 AM" src="https://github.com/user-attachments/assets/26e5684f-598f-4f52-89ac-d23db75de694">

**Comment by mikeldking** [comment]
Linking and closing @jlopatec
