### ISSUE TITLE
LangChain OpenAI Streaming not capturing token counts with stream_usage 

### ISSUE THREAD

**Issue by monuminu** [Arize-ai/openinference#637]
**Describe the bug**
Streaming with LangChain Instrument not capturing llm.token_count.total, llm.token_count.prompt, llm.token_count.completion

**To Reproduce**
`from langchain_openai import ChatOpenAI
from openinference.instrumentation import using_attributes
from openinference.instrumentation.langchain import LangChainInstrumentor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor

endpoint = "http://127.0.0.1:6006/v1/traces"
tracer_provider = trace_sdk.TracerProvider()
tracer_provider.add_span_processor(SimpleSpanProcessor(OTLPSpanExporter(endpoint)))
tracer_provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))

LangChainInstrumentor().instrument(tracer_provider=tracer_provider)
from langchain_openai import AzureChatOpenAI, ChatOpenAI
from langchain.chains import LLMChain
from langchain_core.prompts import PromptTemplate

prompt_template = "Tell me a {adjective} joke"
prompt = PromptTemplate(input_variables=["adjective"], template=prompt_template)
llm = ChatOpenAI(streaming = True, stream_usage = True)
chain = LLMChain(llm=llm, prompt=prompt, metadata={"category": "jokes"})
completion = chain.predict(adjective="funny", metadata={"variant": "funny"})
print(completion)`

**Expected behavior**
llm.token_count.total, llm.token_count.prompt, llm.token_count.completion should be captured for both streaming and non streaming case .

**Screenshots**
<img width="308" alt="image" src="https://github.com/user-attachments/assets/2a201c84-8a02-49a4-a916-3fb0f1eaf9ee">

**Comment by mikeldking** [comment]
Hi @monuminu thanks for your issue. I think this might related to how you have OpenAI configured. OpenAI actually only provides us with tokens with streaming if there is a special flag set.

To get token counts when streaming, install openai>=1.26 and set stream_options={"include_usage": True} when calling create. Below is an example Python code snippet. For more info, see [here](https://community.openai.com/t/usage-stats-now-available-when-using-streaming-with-the-chat-completions-api-or-completions-api/738156).

```python
response = openai.OpenAI().chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Write a haiku."}],
    max_tokens=20,
    stream=True,
    stream_options={"include_usage": True},
)
```

Can you give this a try? Thanks!

**Comment by mikeldking** [comment]
Oh I see you have stream_usage turned on I see. Sorry I misread that. Let me try this code path and let you know.

@monuminu can you give me the versions of instrumenation, langchain, and openAI you are using when you get a chance?

**Comment by monuminu** [comment]
Hi @mikeldking I am using all latest version of the code. langchain, openinference-instrumentation-langchain. Its working fine for OpenAI but not for langchain.

**Comment by monuminu** [comment]
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/882e2e26-fc40-44d7-ae31-b20e3c7414cb">
last one is non streaming and first 2 are streaming

**Comment by mikeldking** [comment]
Thanks @monuminu for the details. We will schedule an investigation for this week. Thanks for your patience.

**Comment by axiomofjoy** [comment]
@monuminu This issue is resolved in `openinference-instrumentation-langchain 0.1.25`
