### ISSUE TITLE
🗺️ Tool calling 

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#689]
- [x] #688 

## Instrumentation
- [ ] #464 
- [x] #834
- [x] #909
- [x] #910
- [x] #908
- [x] [tools] schema definition for openai python SDK
- [ ] [tools] tool definitions for langchain
- [ ] [tools] tool definitions for llamaindex

**Comment by jgomes168** [comment]
Linking the [Function Calling Prompt Playground PRD](https://arizeai.atlassian.net/wiki/spaces/PROD/pages/627769350/Function+Calling+in+Prompt+Playground) so it's clear what we're building on our side. Also looping in @nickleach (probably good to subscribe to this ticket)

**Comment by mikeldking** [comment]
Closing for now as MVP is complete. All else can be enhancements
