### ISSUE TITLE
Rename `TraceConfig` & `CensoredSpan`

### ISSUE THREAD

**Issue by fjcasti1** [Arize-ai/openinference#692]
Current naming:
```
class _CensoredSpan(wrapt.ObjectProxy):  ...

class ConfigTracer(wrapt.ObjectProxy):  ...
```

Alternatives for `_CensoredSpan`:
* `_CuratedSpan`
* `_RedactedSpan`
* `_ConfigSpan`
* `_MaskedSpan`
* `_FilteredSpan`
* `_HiddenSpan`
* `_ObscuredSpan`

I don't personally have suggestions for `ConfigTracer` other than `OpenInferenceTracer`

Thoughts @mikeldking @RogerHYang @anticorrelator ?

**Comment by mikeldking** [comment]
I like `OpenInferenceTracer` and `_MaskedSpan` @fjcasti1

**Comment by fjcasti1** [comment]
> I like `OpenInferenceTracer` and `_MaskedSpan` @fjcasti1

coming up!
