### ISSUE TITLE
🗺️ Anthropic Instrumentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#880]
- [x] [anthropic] dogfooding
- [x] [anthropic] documentation on arize
- [x] [anthropic] documentation on phoenix
- [ ] [anthropic] add to release notes
- [ ] [anthropic] add to opentelemetry.io
- [x] #950
- [x] #953
- [x] #986

**Comment by Parker-Stafford** [comment]
multi turn conversation doesn't include output for some of the messages in the middle

![image](https://github.com/user-attachments/assets/218b1c04-122c-4bec-bed4-cd7ce3e982dd)

**Comment by axiomofjoy** [comment]
Missing tool messages in inputs.

<img width="1589" alt="Screenshot 2024-08-22 at 2 18 16 PM" src="https://github.com/user-attachments/assets/85eb15bd-8c47-4b68-b67d-1df0918b6163">

See `python/instrumentation/openinference-instrumentation-anthropic/examples/end_to_end_tool_use.py`

**Comment by exiao** [comment]
For future reference, if you use any of anthropic's beta features which use client.beta.messages.create, the auto-instrumentor fails to log the LLM calls.

An example. https://docs.anthropic.com/en/docs/build-with-claude/pdf-support#pdf-support-with-prompt-caching

**Comment by axiomofjoy** [comment]
> For future reference, if you use any of anthropic's beta features which use client.beta.messages.create, the auto-instrumentor fails to log the LLM calls.

Thanks @exiao. I think it's probably alright to add support for those features once they are out of beta unless we have users actively requesting them.
