### ISSUE TITLE
[bug] BedrockInstrumentor not working for Embeddings

### ISSUE THREAD

**Issue by glmourad** [Arize-ai/openinference#954]
**Describe the bug**

BedrockInstrumentor throwns error when creating embeddings from AWS Bedrock service.

**To Reproduce**
Steps to reproduce the behavior
    embeddings = BedrockEmbeddings(
        client=boto3.client(
            service_name="bedrock-runtime",
            region_name="eu-central-1",
        ),
        endpoint_url="eu-central-1",
        model_id="cohere.embed-multilingual-v3",
    )

    print(await embeddings.aembed_query(query1))

  File "...............\.venv\Lib\site-packages\langchain_aws\embeddings\bedrock.py", line 156, in _embedding_func
    raise ValueError(f"Error raised by inference endpoint: {e}")
ValueError: Error raised by inference endpoint: 'prompt'

**Expected behavior**
Trace available on Arize Phoenix

**Desktop (please complete the following information):**
 - OS: Windows 10, Python 3.11

**Comment by mikeldking** [comment]
Sorry you are hitting this issue @glmourad we will take a look

**Comment by axiomofjoy** [comment]
Hey @glmourad, thanks for reporting. From the stacktrace, this does not appear to be an OpenInference issue. It looks like you may be missing a prompt parameter.

**Comment by glmourad** [comment]
Hi @axiomofjoy  the code runs smoothly if I simply comment 

BedrockInstrumentor().instrument()

**Comment by axiomofjoy** [comment]
Thanks @glmourad. Can you send a snippet where I can comment/ uncomment the `BedrockInstrumentor().instrument()` line to reproduce?

I haven't tested, but it sort of looks like the LangChain `BedrockEmbeddings` API may not be compatible with the "cohere.embed-multilingual-v3" model. The error message suggests that the [legacy `invoke_model` method](https://github.com/langchain-ai/langchain/blob/99f9a664a5381d4bcd0d38397b604cd562d4452c/libs/community/langchain_community/embeddings/bedrock.py#L139) expects a "prompt" key, but that does not appear to in the [`body` when using the Cohere model](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-embed.html#api-inference-examples-cohere-embed).

```python
        body = json.dumps({
            "texts": [
                text1,
                text2],
            "input_type": input_type,
            "embedding_types": embedding_types}
        )
```

**Comment by glmourad** [comment]
Hello,

Seems it is not working to any embedding model from bedrock:

import boto3
from langchain_aws import BedrockEmbeddings
from openinference.instrumentation.bedrock import BedrockInstrumentor

if __name__ == "__main__":

    BedrockInstrumentor().instrument()

    embeddings = BedrockEmbeddings(
        client=boto3.client(
            service_name="bedrock-runtime",
            region_name="eu-central-1",
        ),
        endpoint_url="eu-central-1",
        #model_id="cohere.embed-multilingual-v3",
        model_id="amazon.titan-embed-text-v1",
    )
    print(embeddings.embed_query("a query"))


here are the dependencies (latest):


opentelemetry-api==1.26.0
opentelemetry-exporter-otlp-proto-http==1.26.0
opentelemetry-instrumentation==0.47b0
opentelemetry-semantic-conventions==0.47b0
openinference-instrumentation-langchain==0.1.27
openinference-instrumentation-openai==0.1.14
openinference-instrumentation-bedrock==0.1.10

boto3==1.34.158

langchain==0.2.14
langchain-core==0.2.35
langchain-community==0.2.12
langchain-openai==0.1.22
langchain-aws==0.1.17
langgraph==0.2.14
tiktoken==0.7.0
