### ISSUE TITLE
Context managers don't work as decorators for async

### ISSUE THREAD

**Issue by harrisonchu** [Arize-ai/openinference#988]
![Image](https://github.com/user-attachments/assets/73238fcb-dcfb-4b0c-bce7-c539249e6972)

**Comment by arizedatngo** [comment]
Curious what's the latest here?

**Comment by axiomofjoy** [comment]
@harrisonchu @arizedatngo Can you provide a code snippet to reproduce the issue? I have a guess at what this ticket means, but not sure.
